### ISSUE TITLE
Setting up SQL 2016 with AWS supplied license fails.

### ISSUE THREAD

**Issue by nbshetty** [aws-quickstart/quickstart-microsoft-sql#10]
The Reconfigure-SQL.ps1 - Line 35
` $params = "-dD:\MSSQL\DATA\master.mdf;-eC:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\Log\ERRORLOG;-lE:\MSSQL\LOG\mastlog.ldf"` seems to suggest it only works for SQL 2014. (MSSQL12).

**Comment by rohit2git** [comment]
@nbshetty Just make a change in the above file to 13 or 14 as per the path existing on your node.

`$params = "-dD:\MSSQL\DATA\master.mdf;-eC:\Program Files\Microsoft SQL Server\MSSQL<13 or 14>.MSSQLSERVER\MSSQL\Log\ERRORLOG;-lE:\MSSQL\LOG\mastlog.ldf"`

After making the change upload it to s3 and re-run.

**Comment by santiagocardenas** [comment]
This should be fixed by #3092462
