### ISSUE TITLE
WSFCFileServerWaitCondition failure

### ISSUE THREAD

**Issue by dougperkes** [aws-quickstart/quickstart-microsoft-sql#15]
I am attempting to create an Always On Sql cluster in an existing VPC. However, I receive the following error when the template runs WSFCFileServerWaitCondition:

```
WaitCondition received failed message: 'Command failure in Disable-WSManCredSSP C:\cfn\scripts\Disable-CredSSP.ps1 on line 5 Exception: System.InvalidOperationException: 
This command cannot be executed because the setting cannot be disabled.
 at System.Management.Automation.MshCommandRun...' for uniqueId: i-0dbd7e32db3e83ba2
```

Has anyone found a good workaround for this issue or might know how I can get things working?

Thanks!

**Comment by kamarja** [comment]
Hi Doug,
This might be a workaround: winrm set winrm/config/client/auth '@{CredSSP="true"}' 
Let us know if that helped.

**Comment by dougperkes** [comment]
Right now I'm using all the samples straight from the AWS quickstart site (https://s3.amazonaws.com/quickstart-reference/microsoft/sql/latest/templates/sql.template). I guess I'll need to download and modify them before trying again. 

Do you know where in the sample I should run the `winrm set...` command?

**Comment by kamarja** [comment]
You can run the Quick Start in your personal bucket. You could create a try/catch block in the Disable-WSManCredSSP script and try running that command if the initial attempt fails. I will try to implement it myself as well when I have a few cycles.

**Comment by kamarja** [comment]
Hi Doug,
Before trying that command, please check the permissions of the Admin user running the command and also if a GPO policy is preventing you from running the command. Thanks.

**Comment by dougperkes** [comment]
Thanks for the suggestions. It turns out we do have a group policy in place that was conflicting with the AWS sample. I downloaded the sample and modified it a bit to match our environment. Things seem to be working better now.
