### ISSUE TITLE
WSFCFileServerWaitCondition failed 

### ISSUE THREAD

**Issue by palanibsm** [aws-quickstart/quickstart-microsoft-sql#17]
Team,

I tried to create this with existing VPC. Getting below issues:

ERROR
<img width="915" alt="cf_error" src="https://user-images.githubusercontent.com/19778526/37009392-9bdce654-214b-11e8-9994-cfeedd18e46c.png">

14:29:37 UTC+1300 | CREATE_FAILED | AWS::CloudFormation::WaitCondition | WSFCFileServerWaitCondition | WaitCondition timed out. Received 0 conditions when expecting 1
-- | -- | -- | -- | --

I tried with different AWS accounts. Still same. I realized this the error occur when it tries to access S3 endpoints. And I have all the scripts in my s3 folder. Prefix also created exactly same. Still failed. One thing I noticed that from the server where it failed, I am unable to connect Internet. I feel S3 is https endpoint. Hence if no internet then probably it can't connect?

**Comment by santiagocardenas** [comment]
Hi @palanibsm 
To launch this Quick Start, you don't need to copy it to your own S3 bucket as long as you leave the default values of Quick Start S3 Bucket Name (QSS3BucketName) and Quick Start S3 Key Prefix (QSS3KeyPrefix) as is.

Are you making your own modifications to the templates which is forcing you to copy them to your own S3 bucket?

**Comment by santiagocardenas** [comment]
Also, are you using your own existing VPC? If so, you need to ensure that the Private Subnets in that VPC can route out to the internet (normally via NAT Gateways). This communication is used to do the CloudFormation signaling that controls the flow of the deployment.

**Comment by palanibsm** [comment]
1) I uploaded the scripts to my own s3 bucket and given that bucket name. I will use the default value and will try again. So this bucket is owned by AWS and available in Sydney region as well? Is it? Because I am creating this stack in Sydney region.
2) My private subnets don't have NAT gateway. So no internet. So, is there anyway I can access s3 without internet?

**Comment by santiagocardenas** [comment]
Answers to your questions:
1. `quickstart-reference` bucket is owned by the AWS Quick Start team. It doesn't need to be in Sydney in order to be accessed and it deploys as expected there (as well as other regions). This is possible due to the use of virtual hosted-style S3 URLs.
2. S3 can be accessed via S3 endpoints, and this is possible if you configure them in your VPC (and should be enough to bootstrap the servers in an environment where you don't want to provide internet access to your private subnets because the CloudFormation signaling uses S3).

**Comment by palanibsm** [comment]
Thank you Santiago...

**Comment by palanibsm** [comment]
Thank you for the solutions. It worked.

**Comment by santiagocardenas** [comment]
You're welcome!
