### ISSUE TITLE
Errors on template and on formation

### ISSUE THREAD

**Issue by aggietallboy** [aws-quickstart/quickstart-microsoft-sql#19]
Hi there, tweaking this to deploy for my environment and noted a couple issues:
First the parameters
1) The 3rd VPC doesn't allow a drop down

2) The key pair name isn't populating the drop down, nor is it accepting input that persists after leaving the field by anything but tab key (clicking mouse anywhere clears the input). Even after using only tab to advance forward, Keypair name is blank

3) BYOL AMI  - anything that can be done to make that a search/dropdown?

4) Security Groups - only pulling a subset of the security groups, I have one that connects up for my on-premise domain, but it's not one of the available choices

5) Service Account name and password - clarification if it merges the domain netbios name + account name, or if it's necessary to enter it

6) Cluster IP Addresses -- it would be awesome if it built these from the AZ/Subnets selected above "automagically"

7) Cluster Node 3 - gray/out/invalidate if witness selected

Tried to submit anyway (to delete after if necessary)

Template Validation Error:
Template validation error: Parameter 'WSFCNode2PrivateIP3' must match pattern ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$

**Comment by aggietallboy** [comment]
Correction - subnet on #1 
Additionally, I have ~18 subnets in the VPC, however only about 5 are showing up in the drop-downs

**Comment by aggietallboy** [comment]
I'm an idiot :D was operating in the wrong zone :)

**Comment by tomharrisonjr** [comment]
@aggietallboy You're not an idiot -- I did the same thing, and every time I load the template it reverts back to Ohio.  This is a bad UI issue with the AWS Console.  I reported it about 5 years ago :-)
