### ISSUE TITLE
Missing SQL Server 2016 Support

### ISSUE THREAD

**Issue by crouffer** [aws-quickstart/quickstart-microsoft-sql#3]
The top-level templates do not support SQL Server 2016, even though there is support in the scripts to download and install it.

**Comment by santiagocardenas** [comment]
@crouffer,
There is support if you use the latest templates:
For New VPC:
sql-master.template

For Existing VPC:
sql.template

We are updating the documentation to allow these to be launched directly.

**Comment by realstrategos** [comment]
sql-master.template does not currently work, is it still being worked on?

**Comment by jaymccon** [comment]
@realstrategos sql-master.template in the master branch works as expected in our tests. 

Are you able to provide any error messages or insight into where you are encountering issues ?

**Comment by realstrategos** [comment]
I got the following errors:
13:11:25 UTC-0400 | CREATE_FAILED | AWS::CloudFormation::Stack | SQLHA-SQLStack-18ZOV3NTINOCR | The following resource(s) failed to create: [WSFCNode1WaitCondition].
-- | -- | -- | -- | --
  | 13:11:24 UTC-0400 | CREATE_FAILED | AWS::CloudFormation::WaitCondition | WSFCNode1WaitCondition | WaitCondition received failed message: 'Command failure in C:\cfn\scripts\Reconfigure-SQL.ps1 on line 104 Exception: System.Management.Automation.RemoteException: Exception calling WaitForStatus with 2 argument(s): Time out has expired and the operation has not been completed.' for uniqueId: i-063003a89952bb27a

Below are the parameters used. Note that I used availability zone 3 as a witness and I updated the fileserver ip to availability zone 3 as per instructions

Stack name:
SQLHA
Network Configuration
AvailabilityZones
us-east-2a,us-east-2b,us-east-2c
ThirdAZ
witness
VPCCIDR
10.0.0.0/16
PublicSubnet1CIDR
10.0.128.0/20
PublicSubnet2CIDR
10.0.144.0/20
PublicSubnet3CIDR
10.0.160.0/20
PrivateSubnet1CIDR
10.0.0.0/19
PrivateSubnet2CIDR
10.0.32.0/19
PrivateSubnet3CIDR
10.0.64.0/19
Amazon EC2 Configuration
KeyPairName
Ohio-SQLServer
HostType
Shared
DedicatedHostAMI
Standard Active Directory Configuration
ADScenarioType
AWS Directory Service for Microsoft AD
DomainDNSName
cureo.com
DomainNetBIOSName
cureo
DomainAdminPassword
·····
Self-Managed Active Directory Configuration (for non-AWS Directory Service architecture)
DomainAdminUser
StackAdmin
ADServer1InstanceType
m4.xlarge
ADServer1NetBIOSName
DC1
ADServer1PrivateIP
10.0.0.10
ADServer2InstanceType
m4.xlarge
ADServer2NetBIOSName
DC2
ADServer2PrivateIP
10.0.32.10
RestoreModePassword
·····
Remote Desktop Gateway Configuration
RDGWCIDR
10.0.0.0/16
NumberOfRDGWHosts
1
RDGWInstanceType
t2.large
Microsoft SQL Server Configuration
SQLServerVersion
2016
SQLServiceAccount
sqlsa
SQLServiceAccountPassword
·····
SQLLicenseProvided
yes
VolumeIops
1000
VolumeSize
500
VolumeType
gp2
Failover Cluster Configuration
WSFCNodeInstanceType
r4.2xlarge
WSFCNode1NetBIOSName
WSFCNode1
WSFCNode1PrivateIP1
10.0.0.100
WSFCNode1PrivateIP2
10.0.0.101
WSFCNode1PrivateIP3
10.0.0.102
WSFCNode2NetBIOSName
WSFCNode2
WSFCNode2PrivateIP1
10.0.32.100
WSFCNode2PrivateIP2
10.0.32.101
WSFCNode2PrivateIP3
10.0.32.102
WSFCNode3NetBIOSName
WSFCNode3
WSFCNode3PrivateIP1
10.0.64.100
WSFCNode3PrivateIP2
10.0.64.101
WSFCNode3PrivateIP3
10.0.64.102
WSFCFileServerInstanceType
t2.small
WSFCFileServerPrivateIP
10.0.64.200
AWS Quick Start Configuration
QSS3BucketName
quickstart-reference
QSS3KeyPrefix
microsoft/sql/latest/

**Comment by jaymccon** [comment]
@realstrategos I have not been able to replicate the error you are experiencing, from what I can see it looks like the SQL service is failing to start after being reconfigured. This reconfiguration only happens when you select yes for the SQLLicenseProvided parameter, as the marketplace AMI already has SQL installed. 

Are you able to re-launch the stack with rollback on failure disabled and have a look in the event viewer for any error codes events that could point to the cause of the sql service failing to start. 

Be sure to delete the stack after investigating, as the License costs for those marketplace AMI's can get expensive if left running.

**Comment by crouffer** [comment]
Thanks.  I will close the issue.
