### ISSUE TITLE
Error while creating stack when executed through aws cli

### ISSUE THREAD

**Issue by mcuervoe** [aws-quickstart/quickstart-microsoft-sql#45]
I am trying to create the stack through the aws cli, so I can maintain the creation parameters into git. 

This is the command that I am executing to create the stack: 

```
aws cloudformation create-stack --stack-name sql-stack --template-url https://aws-quickstart.s3.amazonaws.com/quickstart-microsoft-sql/templates/sql-master.template --parameters file://parameters.json --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --on-failure DO_NOTHING
```

However, the clouldformation always fails on the SQLStack template, complaining about not having permissions on S3.

What I am doing wrong? When I execute the template through the AWS console, everything works as expected, using exactly the same parameters passed on the command line

**Comment by virtlima** [comment]
mcuervoe, 

Thanks for reaching out, can you try cloning the project and copying its contents to a S3 bucket in your account and testing keeping the prefix the same but modifying the QSS3BUCKET Parameters. I am going to attempt the same test on my end. You could also utilize our tool taskcat[](https://aws-quickstart.github.io/taskcat/). Taskcat will do this automatically for you as well.

**Comment by virtlima** [comment]
I was able to successfully launch the quick start using the same command line and the attached parameter file. Can you verify if your QSS3BucketName parameter set to aws-quickstart. 
[test.json.txt](https://github.com/aws-quickstart/quickstart-microsoft-sql/files/3330337/test.json.txt)

**Comment by mcuervoe** [comment]
Thanks for the quick answer. And yes, you were right. I have a problem with this parameter. I was able to launch it now correctly
