### ISSUE TITLE
EBS Volume issues

### ISSUE THREAD

**Issue by manuelh2410** [aws-quickstart/quickstart-microsoft-sql#55]
For the SQL node configuration, (SQL Server configuration) 
EBS volumes smaller than "2049 GiB" are automatically initialized by the Ec2config "Ec2InitializeDrives" Plugin  using the MBR partition style which makes extending the volumes beyond this size impossible .
same holds true for ec2-launch.
==
Ec2config Ec2InitializeDrives plugin initializes secondary EBS volumes smaller than "2049 GiB" with the MBR partitioning scheme 
instead of GPT . 
This causes extending the drives to a size beyond 2TB  impossible which is very inconvenient for volumes storing SQL databases . 
  
Is there any way we can add optional parameters to the "Ec2InitializeDrives "  plugin , to allow customers the option of selecting the desired partitioning scheme? or just allow the 
Ec2InitializeDrives "  plugin to initialize all secondary volumes as GPT instead of MBR? 

==
In EC2launch this  also holds true for volumes smaller than "2048 GIB" which also get initialized as MBR volumes . 

I tested this by linking two ebs volumes to the instance and manually running the following script 
C:\ProgramData\Amazon\EC2-Windows\Launch\Scripts\InitializeDisks.ps1
==
It looks like this cloud formation template is configured to initialize the drives automatically . 
this causes a problem for  customers who at launch selected drive sizes smaller than "2049 GiB"  for ec2config or "2048" for ec2launch

**Comment by manuelh2410** [comment]
Example of config : 

Provisioned IOPS for the SQL data, logs and tempDb volumes. 
This parameter is applicable only when the SQL Server volume type is set to "io1".
    MaxValue: '20000'
    MinValue: '100'
    Type: Number
  VolumeSize:
    Default: '500'

Description: 'Volume size for the SQL data, logs and tempDb volumes, in GiB.'
    MaxValue: '16000'
    MinValue: '100'
    Type: Number
========

What is the plan for customers who have reached a point where they require a volume size larger than
"2049 GiB" ?

**Comment by davmayd** [comment]
I've created a PR to address this issue

**Comment by davmayd** [comment]
The Quick Start has been updated to format all volumes using GPT instead of MBR
