### ISSUE TITLE
ad-3.template now requires KeyPairName

### ISSUE THREAD

**Issue by ephenix** [aws-quickstart/quickstart-microsoft-sql#65]
Deploying this quickstart started failing last week due to submodules being updated.
```
The following resource(s) failed to create: [ADStack]. . Rollback requested by user.
2020-03-09 01:07:05 UTC-0600	ADStack	CREATE_FAILED	Parameters: [KeyPairName] must have values
2020-03-09 01:07:04 UTC-0600	ADStack	CREATE_IN_PROGRESS	-
```

This is the commit that broke things: 
 Submodule quickstart-microsoft-activedirectory updated from f1b70b to d69ddf 

Over on the quickstart-microsoft-activedirectory project, they added the KeyPairName parameter to the AD-3 template in that range.

**Comment by davmayd** [comment]
This has been done
