### ISSUE TITLE
shared storage using FSx?

### ISSUE THREAD

**Issue by jyjohnson** [aws-quickstart/quickstart-microsoft-sql#73]
Could you add an option to use FSx for the DB volumes instead of EBS?

Thanks.

**Comment by foibleless** [comment]
I would also like to see that

**Comment by davmayd** [comment]
@jyjohnson we recently published a SQL FCI Quick Start that uses FSx for shared storage. https://github.com/aws-quickstart/quickstart-microsoft-sql-fci-fsx
