### ISSUE TITLE
AWS DS Enterprise and submodules directory

### ISSUE THREAD

**Issue by jyjohnson** [aws-quickstart/quickstart-microsoft-sql#74]
Why is AWS DS "Enterprise" specified (vs standard)?
Is anything supposed to be in the **\submodules\** directories?

**Comment by davmayd** [comment]
@jyjohnson the Active Directory Quick Start supports either Standard or Enterprise editions, you can set the ADEdition parameter  to "Standard" if you prefer Standard. The submodules directory should contain links to the VPC, AD, and RD Gateway Quick Starts. You can run `git submodule update --init --remote` to populate the directories.
