### ISSUE TITLE
Setup option for self-managed AD

### ISSUE THREAD

**Issue by GregSteiner** [aws-quickstart/quickstart-microsoft-sql#87]
It would be nice to have an option for Self-Managed AD, or to omit the AD steps in the quickstart so we can manage that ourselves.

**Comment by davmayd** [comment]
Those options are already there. If deploying into a new VPC you can select "Microsoft AD on Amazon EC2" as the Active Directory scenario (https://github.com/aws-quickstart/quickstart-microsoft-sql/blob/main/templates/sql-master.template#L214). If you want to use an existing Active Directory you can deploy into an existing VPC and enter your AD values.
