### ISSUE TITLE
Architecture Diagram Visualization 

### ISSUE THREAD

**Issue by kaustubhkelkar** [aws-quickstart/quickstart-microsoft-sql#94]
Hi @davmayd ,

I came across your repo and I took the liberty to scan it with the tool that I am developing. If I caught your attention, feel free to take a look at the [following diagram](https://dashboard.codeshield.io/public/result/beed3344-47ea-489c-96e8-40d33154c2e4?utm_source=github.com&utm_medium=share-graphs&utm_campaign=teamB) and let us know your thoughts on this. I am really interested to get your feedback and understand if the diagram we presented matches the architecture you have in mind.

**Comment by davmayd** [comment]
Hi @kaustubhkelkar. That's a nice visualization that matches the EC2 instances and EBS volumes that are created. We're always interested in products that can automatically generate architecture diagrams for us. Unfortunately AWS has a specific format that's required for architecture diagrams; see http://aws-quickstart.github.io/quickstart-microsoft-sql/#_architecture for the SQL Quick Start diagrams.

**Comment by kaustubhkelkar** [comment]
Hi @davmayd, thanks a lot for the feedback!

I would like to know more about the AWS-specific format you mentioned earlier. Could you please provide a link to an official specification for the format? Also, did you create the diagrams mentioned [here](http://aws-quickstart.github.io/quickstart-microsoft-sql/#_architecture) manually?

**Comment by davmayd** [comment]
Hi @kaustubhkelkar . Yes, the architecture diagram was created manually in PowerPoint. You can find the official icons and design guidance here: https://aws.amazon.com/architecture/icons/
